### ISSUE TITLE
[FEAT] updateAllChanges

### ISSUE THREAD

**Issue by jelliijoa** [Team-Picle/Picle-Server#25]
## 🫧 Description
[ #35 이슈 이후에 기능 별로 나눠서 이슈 생성하고 푸쉬했어야 했는데
맥북 수리로 인해 아직 푸쉬하지 않았던 #25에 변경사항 전체 푸쉬합니다. ]

### Todo 추가/수정 사항
- [x] 클라 요청으로 getCompletedByDate 삭제
- [x] 투두 updateTodo, deleteTodo 수정 >> findById -> findByIdAndUserId로 리포지토리와 함께 수정

### Routine 추가/수정 사항
- [x] 클라 요청으로 getCompletedByDate 삭제
- [x] preview 기능 추가로 인한 ERD 및 Routine domain 수정
- [x] preview 기능 추가로 인한 get Previews 추가 / getByDate 수정
- [x] preview 기능 추가로 인한 createPreview 추가
- [x] 루틴 이미지 등록 시 사용자의 현재 위치 정보를 통해 루틴 위치 반경 50m 내에 있는 경우 검증 추가
- [x] 루틴 이미지 등록 시 미리 등록해 둔 루틴 이미지와 이미지 유사도 검증 추가
- [x] 루틴 이미지 유사도 검증을 위한 Flutter 코드 구현 / 연동 (ImageVerificationService)
- [x] 루틴 미리보기 정보를 수정하는 updatePreview api 추가
- [x] 피드 기능 변경으로 인한 FeedResponseDto 및 getMyFeeds / getAllFeeds 추가
- [x] 클라에서의 루틴 종료 / 삭제 구분을 위해 finishRoutine / deleteRoutine으로 api 분리
